TownyAdvanced/FlagWar

src/main/java/io/github/townyadvanced/flagwar/FlagWarAPI.java, src/main/java/io/github/townyadvanced/flagwar/events/CellAttackEvent.java
This Hotfix PR fixes the inconsistency of the War Flag Timer (`flag.waiting_time`) being applied to the length of a phase, rather than the overall war flag.
The waiting_time should now apply to the total lifetime of the war flag, rather than the respective phase.
____
Changed the CellAttackEvent to set it's timer based on the MaterialShiftTime (phase time) rather than the `flag.waiting_time` configuration node (full time). 
____
closes #35 
____
- Confirmed to now work as expected. Tested with a configuration time of 1 minute.
---
changes are mine and are not encumbered by any other license or …
=> Hotfix: Make `flag.waiting_time` work as expected

src/main/java/io/github/townyadvanced/flagwar/i18n/LocaleUtil.java
Fixes Issue #43 
____
Fixes TownyAdvanced/FlagWar#43
____
---
knowledge.
=> Fixing Issue #43: Localization problems on paper 1.16.X with java 16.

.gitignore, src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/resources/config.yml
min_online_in_town_to_attack: 2
min_online_in_nation_to_attack: 3
Are added to the config, making it possible to require separate numbers for required attackers.
____
Via two new methods:
```
checkIfAttackingTownHasMinOnlineForWar(attackingTown);
checkIfAttackingNationHasMinOnlineForWar(attackingNation);
```
the attacking side is tested for the new config values.
____
Closes #70 
____
---
knowledge.
=> Adds new config options for specific attackers required to be online.

src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarBlockListener.java
Simply adds a test when the flag is placed, skipping if the TownyWorld has warAllowed false.
____
____
____
---
knowledge.
=> Make flagwar behave according to whether towny allows war in the world.

pom.xml, src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarCustomListener.java, src/main/resources/config.yml
Fixes setting lost in TownySettings during EventWar purge.
____
____
____
---
knowledge.
=> Add nations_can_toggle_neutral rule to the config.

src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/FlagWarAPI.java, src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/events/CellAttackEvent.java, src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarCustomListener.java, src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java
Re-introduction of #89, fixing #97.
____
- Return `Instant.MAX` instead of `Instant.EPOCH` when a town is not in the `TOWN_LAST_FLAGGED_HASH_MAP`.
- This turned out to be an issue as I had forgotten to validate timestamps being after the epoch at the problem's downstream implementation, `FlagWarCustomListener#isAfterFlaggedCooldownActive(Town)`. 🤡 
____
#97, #89
____
---
knowledge.
=> Re-merge Time API and fix issue validating against the time a town was last flagged, if it has never been flagged.

Contributors.md, src/main/resources/Translation_ru_RU.properties
Add a translation into Russian
____
Add **Translation_ru_RU.properties** **to src/main/resources**
____
---
knowledge.
=> Add russian language

src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java
Errors are thrown when FW tries to check if a block being broken is part of the beacon, when the beacon system is not being used.
____
____
Closes #100.
____
---
knowledge.
=> Fix beacon blocks being checked against when beacons are false in the config.

src/main/java/io/github/townyadvanced/flagwar/FlagWar.java
The flagwar class wasn't keeping up with the pom.
____
0.98.1.0 is used in place of 0.97.3.0 to ensure servers have the API we're using.
____
____
---
knowledge.
=> Update the static min towny versions

src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/resources/Translation_en_US.properties, src/main/resources/Translation_es_MX.properties, src/main/resources/Translation_fr_FR.properties, src/main/resources/Translation_ru_RU.properties, src/main/resources/config.yml
Adds 2 new config options, one which enables the feature and another
which sets how many neighbouring plots are required to protect a plot.
This feature is similar to the attack edge plots only, but further slows
attackers by requiring that they attack from a corner and chip away at a
town in order to get to their homeblock.
____
The feature is off by default, but when it is enabled it will require 3
neighbouring plots to grant protection.
____
Closes https://github.com/TownyAdvanced/FlagWar/issues/74.
____
---
changes are mine and are not encumbered by any other license or restriction to the …
=> Feature: Neighbouring plots protect from attack.

src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java
Fixes the NPE seen below: https://pastebin.com/kwe0rpXs
____
null check is added.
____
____
---
knowledge.
=> Fixes a potential NPE when the hologram thread is null when an attack is cancelled.

README.md
=> Correct version number typo.

pom.xml
I'm updating the version number for release.
____
____
____
---
knowledge.
=> Update pom.xml for release version.

pom.xml, src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java, src/main/resources/plugin.yml
Adds support for Folia's multi-threading system. Also increases the min. required version of Towny.
____
Changes the one instance that FW uses the server scheduler, adds the boiler plate Towny method of getting and setting a TaskScheduler based on whether the server uses Folia/Paper or not-Folia/Paper.
____
____
---
knowledge.
=> Add support for Folia, bump min. Towny version to 0.100.0.0.

src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/events/CellAttackEvent.java, src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java
Follow up PR that takes care of a 2nd un-noticed use of the BukkitScheduler.
Removes a now unneeded Towny instance being passed around.
____
____
____
---
knowledge.
=> Do a better job of implementing Folia.

CHANGELOG.md, pom.xml, src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java
=> Fix attack tasks not being cancelled correctly.

pom.xml, src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarCustomListener.java
Towny had a relocation of Transaction and TransactionType, this PR adapts to that relocation with not other required changes.
____
____
____
---
knowledge.
=> Update for breaking TransactionType change post 0.100.3.7.

pom.xml
=> Update version number for release.

src/main/resources/Translation_zh_CN.properties
Add zh_CN translate to FlagWar
____
Add zh_CN translate, and I already tested it on my server
```
[18:00:22 INFO]: [FlagWar] Enabling FlagWar v0.6.3
[18:00:22 INFO]: [FlagWar] Using locale: 简体中文 (中国) - 1.2
[18:00:22 INFO]: [FlagWar]
▄████  █    ██     ▄▀        ▄ ▄   ██   █▄▄▄▄
█▀   ▀ █    █ █  ▄▀         █   █  █ █  █  ▄▀
█▀▀    █    █▄▄█ █ ▀▄      █ ▄   █ █▄▄█ █▀▀▌
█      ███▄ █  █ █   █     █  █  █ █  █ █  █
█         ▀   █  ███       █ █ █     █   █
▀           █              ▀ ▀     █   ▀
▀                      ▀
[18:00:22 INFO]: [FlagWar] Copyright © 2021–2023 TownyAdvanced
[18:00:22 INFO]: [FlagWar] 正在检查 Towny...
[18:00:22 WARN]: [FlagWar] 运行的 Towny 版本比当前的 FlagWar 版本更新。你是否已更新？
[18:00:22 INFO]: [FlagWar] 注册监听器...
[18:00:22 INFO]: [FlagWar] 监听器已注册。
[18:00:22 INFO]: [FlagWar] …
```
=> translate to zh_CN

pom.xml
=> Bump version number for release.

.github/workflows/compile-on-push.yml, pom.xml
Updating Paper-API requires a bump to Java.
____
Altering the pom with a working paper-api repo and version bump, and workflow java version, to see if we can compile-on-push without errors.
____
____
---
knowledge.
=> Update compile-on-push workflow to use Java 21

src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/listeners/WarzoneListener.java, src/main/resources/config.yml
=> Make the height that is protected configurable as well.
