TownyAdvanced/FlagWar

src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java, src/main/java/io/github/townyadvanced/flagwar/util/Messaging.java, src/main/java/io/github/townyadvanced/flagwar/util/package-info.java, src/main/resources/config.yml
Closes #34 - Issue result of mismatched configuration keys in the FlagWarConfig class, as well as a comparative error. Both were tracked down by introducing a debugging method, through a messaging utility class.
The keys would default to 0, thus throwing the calculation math off and making beacon minHeight equal to the top of the flag; instead of topOfTheFlag + configuration minHeight. And the comparison was set for if minBlock greater than the top of the flag base block, to return and not draw the beacon.
Also possibly fixes a previously uncaught Time-to-wait-after-flagged setting issue - another case of using the wrong key.
____
- New: Messaging Class (`io.github.townyadvanced.flagwar.util.Messaging`)
- Two Debug message methods: debug(String) and debug(String, Object[])
- Appends …
=> Fix Beacons & Time-to-wait-after-flagged, Introduce Messaging util w/Debug messages

src/main/java/io/github/townyadvanced/flagwar/i18n/Translate.java
Fix "&'" color code parsing in FlagWar messaging. In the future it will enable 1.16+ hex color codes as well.
____
Made strings from i18n.Translate#from() go through Towny's Colors#translateColorCodes() method.
____
#33 
____
---
knowledge.
=> Fix Bukkit "&" Color Code Parsing

src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/i18n/Translate.java, src/main/resources/config.yml
Add alternative flag timer materials. Granular intervals can be achieved as originally suggested by adding multiple entries to the config. For example, 3 entries of ancient debris, 5 of obsidian, and a flag length of 8 minutes would satisfy the example in the original suggestion.
____
* Add logger to FlagWarConfig
* Used in #getCustomTimerBlocks()
* Move old classic wool TIMER_MATERIALS to DEFAULT_TIMER_MATERIALS
* Add boolean #isUsingDefaultTimerBlocks
* Used in new TIMER_MATERIALS
* Checks config boolean value "timer_blocks.use_default"
* Add new TIMER_MATERIALS
* Checks value of #isUsingDefaultTimerBlocks()
* If true, is set to DEFAULT_TIMER_MATERIALS
* If false, is set to #getCustomTimerBlocks()
* Add #getCustomTimerBlocks()
* Gets list of materials from config.yml, …
=> Add Feature: Alternative Flag Timer Materials

.github/workflows/compile-on-push.yml, .github/workflows/deploy-on-release.yml, .idea/compiler.xml, README.md, pom.xml, src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/listeners/WarzoneListener.java, src/main/java/io/github/townyadvanced/flagwar/objects/Cell.java, src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java
This PR is does the following:
- Updates the build environment for Java 16 and Paper 1.17
- Removes the `alternatives` maven profile, as it conflicts with the build.
- Restore  `WarzoneListener` to functionality, without failing over onBuild / onDestroy events.
- Removes the deprecated `CellUnderAttack#isFlag(Block)` method.
____
- Testing done on Paper 1.17, build 20; Towny 0.97.0.6; using a non-operator, permission-free user.
---
knowledge.
=> Update development target to Minecraft 1.17; Restore WarzoneListener

pom.xml, src/main/java/io/github/townyadvanced/flagwar/HologramUpdateThread.java, src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java, src/main/resources/config.yml, src/main/resources/plugin.yml
Adds configurable holograms that spawn above war flags. The hologram is defined by lines. There are four line types: item, text, timer, and empty. Item lines are floating items. Empty and text lines are self explanatory. Most notably, timer lines can be used to show the time remaining on a war flag, a great QOL feature, and especially useful if you might be using alternative timer materials. Color codes are supported in all text, and the formatting of the timer is extremely customisable.
<details>
<summary>Demo (GIF)</summary>
</details>
____
* Add boolean #isHologramEnabled
* Used to cache result of #isHologramEnabled(boolean checkConfig)
* Returned by #isHologramEnabled()
* Add #HOLOGRAM_SETTINGS
* Stores parsed hologram settings from config
* Checks value of #isHologramEnabled via …
=> Add War Flag Holograms

CHANGELOG.md, pom.xml, src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/FlagWarAPI.java, src/main/java/io/github/townyadvanced/flagwar/listeners/OutlawListener.java, src/main/resources/Translation_en_GB.properties, src/main/resources/Translation_en_US-POSIX.properties, src/main/resources/Translation_en_US.properties, src/main/resources/Translation_en_US_POSIX.properties, src/main/resources/Translation_es_MX.properties, src/main/resources/config.yml
Adds an new `OutlawListener` class that listens to the Towny `OutlawTeleportEvent`.
Also, adds `FlagWarAPI#isUnderAttack(Nation)`.
____
If an outlawed player is in enemy territory, while the said enemy is under attack, the event should be canceled to prevent escape. This should also come into effect if the player is within an enemy's NationZone. If the event is fired, while the outlawed player is within their own territory, or an allies,  the event will *not* be canceled.
The outlaw is only notified when they cannot teleport.
This can be extended in the future with configurable switches (such as allowing cancellation regardless of who owns the territory, or if this listener should be disabled all together.)
____
Closes #60 
____
---
By making this pull request, I represent that I have …
=> Feature: Add OutlawListener, cancel OutlawTeleportEvents; API: Add isUnderAttack(Nation)

src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarCustomListener.java, src/main/resources/config.yml
New Config option:
```
prefer *not* dealing with that.
flag_unclaims_townblocks: false
```
____
Adds a third option for unclaiming, which will take precedent over the `flag_takes_ownership_of_town_blocks: true` option, by modifying this event:
```java
private void transferOrUnclaimOrKeepTownblock(final Town atkTown, final TownBlock townBlock, final Town defTown) {
if (FlagWarConfig.isFlaggedTownBlockUnclaimed())
unclaimTownBlock(townBlock);
else if (FlagWarConfig.isFlaggedTownBlockTransferred()) {
transferOwnership(atkTown, townBlock);
} else {
String message = Translate.fromPrefixed("area.won.defender-keeps-claims");
TownyMessaging.sendPrefixedTownMessage(atkTown, message);
TownyMessaging.sendPrefixedTownMessage(defTown, message);
}
}
```
The comments of the overriden config option have …
=> Adds new option to the config to unclaim won townblocks.

src/main/java/io/github/townyadvanced/flagwar/listeners/OutlawListener.java
Gathering the town using a null townblock threw an NPE.
____
Getting the town from the outlaw's location returns the town or null if not present, using a different TownyAPI method.
____
- Closes #78
____
---
knowledge.
=> Fix NPE in OutlawListener

src/main/java/io/github/townyadvanced/flagwar/objects/Cell.java
On all parse(WorldCoord) tests, the worldcoord's were being treated like location x/z's.
____
WoorldCoords now return a new Cell directly.
____
Closes #93
____
---
knowledge.
=> Fix Cell#parse(WorldCoord)

src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/FlagWarAPI.java, src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/events/CellAttackEvent.java, src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarCustomListener.java, src/main/java/io/github/townyadvanced/flagwar/objects/CellUnderAttack.java
Replaces most usages of long for storing timestamps and durations with the `java.time` API. Most values are now either stored as `java.time.Instant` or `java.time.Duration`.
____
- Flag Timer Phases now stored as `java.time.Duration` and converted to ticks only when ticks are needed.
- Timestamps for when a town was last flagged are now stored as `java.time.Instant`, with null/0 now mapped to `Instant.EPOCH`.
- Ticks calculated from millisecond precision use timeMillis / 50. The value is floored to the whole tick (int math).
- Deprecates some methods while attempting to preserve their functionality until removed.
____
____
---
have submitted under the terms of the accompanying license …
=> Initial Use of the Java.Time API

src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarCustomListener.java
These methods were already being prefixed by FlagWar's prefix, and by
sending it to TownyMessaging was adding another Towny prefix.
FlagWar is already handling Translations to other languages, so I don't
think we have to worry about Translatable objects in FlagWar.
____
____
____
---
knowledge.
=> Remove deprecated calls to TownyMessaging.sendResidentMessage.

src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java
Any empty list currently opts to allow all materials, but this behaviour
is not documented in the config, so I changed it to actually be empty.
____
____
____
---
knowledge.
=> Allow for an empty editable materials list.

src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java
The FlagWarConfig was not using TimeTools to parse the config's value into milliseconds.
____
It now parses using TimeTools, or falls back to the default value.
____
Closes #115.
____
---
knowledge.
=> Fix FlaggedInteractCooldown not parsing with TimeTools.

src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarCustomListener.java
Feature was wired up backwards and using the wrong TimeTools method.
____
Swapped TimeTools#getSeconds for TimeTools#getMillis.
Negated the return of isAfterFlaggedCooldownActive from using isAfter to isBefore.
____
____
---
knowledge.
=> Fix flagged-town-feature not working.

src/main/java/io/github/townyadvanced/flagwar/listeners/WarzoneListener.java
Correctly finishes choosing an outcome for the destroy-tests related to the editable materials list in the config.
____
Adds a return where there wasn't.
____
____
---
knowledge.
=> Fix TownyDestroyEvent Listener being indecisive.

.github/workflows/compile-on-push.yml, pom.xml, src/main/java/io/github/townyadvanced/flagwar/FlagWar.java, src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarBlockListener.java, src/main/java/io/github/townyadvanced/flagwar/listeners/WarzoneListener.java
This PR updates FlagWar to 0.5.4-SNAPSHOT.
Minimum requirements for operation change:
- Java 17+ required (JDK 16 support removed)
- Towny 0.98.3.11 is now the minimum compatible version of Towny.  (Targets 0.98.4.0 _Stable_)
- Required to drop deprecated call.
-  Errata changes:
- In addition to the documentation, CC-BY-4.0 covers any artistic assets hosted (e.g. a future FlagWar logo, documentation visual aides, etc.)
- Updated console copyright tagline to '2021-2023'.
=> Bump Snapshot and Baseline Targets

.github/FUNDING.yml, README.md, pom.xml
I have not displayed an adequate level of involvement with its maintenance over the last year. If anything, the last major commit would have been in August, just before releasing 0.5.3. The majority of contributions since have come from @LlmDl and automated dependency updates. So, given that I cannot seem to dedicate enough time, I will be stepping down as its maintainer. Please see the Discord for more information, and on-going efforts.
This PR tracks clerical changes necessary to transfer to a new maintainer. Things will be added to it as I come across them.
____
- Remove link to GitHub Sponsors (Personal Only)
- Update roles in POM
- Remove instruction to Ping on Readme - direct to '#flagwar' channel instead.
=> Transfer of Maintainership

CHANGELOG.md, pom.xml
=> Update files for 0.6.0 release.

src/main/java/io/github/townyadvanced/flagwar/config/FlagWarConfig.java, src/main/java/io/github/townyadvanced/flagwar/listeners/WarzoneListener.java, src/main/resources/config.yml
Makes it so that the editable materials cannot be used too close to the flag.
____
Adds 
```
protected_area_surrounding_flag: 0
```
To the warzone section of the config.
____
Closes #398.
____
---
knowledge.
=> Add the ability to protect an area surrounding the flag from building.

pom.xml, src/main/java/io/github/townyadvanced/flagwar/listeners/FlagWarCustomListener.java
When run at LOWEST no plugin could act on the CellWonEvent without cancelling the event and then re-firing it (and potentially not getting it in before FlagWar operates off of it anyways.)
____
This change makes the FW plugin act upon its own CellWonEvent on MONITOR priority, after other plugins have had their chance at listening/cancelling it on all of the other, lower priorities.
____
Closes #405.
____
---
knowledge.
=> Fix CellWonEvent being unable to be acted upon.

jitpack.yml
Jitpack.yml still had java 17, causing 0.7.0 not to build: https://jitpack.io/com/github/TownyAdvanced/FlagWar/0.7.0/build.log
____
Updated jitpack.yml to use Java 21.
____
____
---
knowledge.
=> Fix jitpack.yml java version not allowing build on the repo.
